### ISSUE TITLE
Any better workarounds for TS7056?

### ISSUE THREAD

**Issue by thure** [colinhacks/zod#1040]
I'm responsible for a project with pretty complex schemas. We're running into a lot of TS compile errors like this:

> error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

The best workaround I've found is to annotate schema declarations with zod types ahead of time (rather than using `z.infer`):

```ts
export type ZBlockEntity = z.ZodUnion<
  [
    typeof paragraphPropsOrElement,
    typeof layoutPropsOrElement,
    ...
    typeof escapeElement
  ]
>
export const blockEntity: ZBlockEntity = z.union([
  paragraphPropsOrElement,
  layoutPropsOrElement,
  ...
  escapeElement,
])
```

TypeScript will declare the array of `typeof name` referentially with this explicit annotation, otherwise it repeats a literal of each schema in the union.

The example I gave was simple, but some schemas that are hitting TS7056 are very tricky to mint and maintain explicit type annotations for, and even if it's achievable it will greatly increase technical inertia for the features that hit that wall.

I'd like to find a way to compile schemas in a way that TypeScript can declare and reuse named types instead of it repeating the same literals so many times it breaks.

Is there a workable solution here, or have we hit a wall?

**Comment by FlorianWendelborn** [comment]
In my experience, TS7056 happens mostly when you’re putting a lot of schemas and other types into the same namespace. For example [here, in `@3yourmind/kotti-ui`](https://github.com/3YOURMIND/kotti/blob/33e5a3158476cb02026c3f19c41f733bce1a666d/packages/kotti-ui/source/types/kotti.ts)

Returning this entire `Kotti` namespace from a vue `setup()` function triggers TS7056. I’ve not yet seen TS7056 in a case where this wasn’t the case, even in a different project with a highly complex (split-up into 20 different files, using lots of preprocess and enums) zod schema.

So, are you perhaps doing this as well? Is the codebase opensource so one could take a look at the exact issue you’re facing?

In the worst-case, you could decide to use [`zod-to-ts`](https://github.com/sachinraja/zod-to-ts) and generate the TS types from a build script. I think that should simplify the type structure quite a bit.

Another optimization could be to handle the parsing in steps. You could declare a part of the schema as `z.unknown` and only parse it (with a different, specialized schema) when you need to.

Additionally, please make sure you’re on the latest TypeScript version, some of the recent versions improve handling of complex types, which _could_ make your problem less common.

**Comment by thure** [comment]
The project is open source, yes. We're getting TS7056 in these examples:

- [Card content item entity](https://github.com/OfficeDev/fluent-blocks/blob/main/packages/react/src/blocks/Card/card-properties.ts#L12-L20)
- [Card props or element](https://github.com/OfficeDev/fluent-blocks/blob/main/packages/react/src/blocks/Card/Card.tsx#L99-L102)

> TS7056 happens mostly when you’re putting a lot of schemas and other types into the same namespace

Letting TS7056 be the test for whether a name shares a file with another feels wrong-headed to me. You can see in the examples we're not exporting very much from the package, it's just very deeply composed.

That composition is why I'm asking, is there a way to cause tsc to _refer_ to types _rather than repeat literals_? This seems to be the real issue.

As it is, maybe rather than the source of truth being zod, it should be TypeScript, and we should use `ts-to-zod`.

**Comment by FlorianWendelborn** [comment]
@thure I’m not sure if this is possible for your project, but as it turns out this issue seems to only happen when `declaration: true` is set in `tsconfig.json`. Since the project I work on that has a similar issue isn’t a library but an app that only consumes libraries, I set `declaration: false` and now TS7056 doesn’t happen anymore.

Just in case that somehow gives you a better idea on how to fix this in https://github.com/OfficeDev/fluent-blocks

**Comment by thure** [comment]
I'm not sure it would… regardless of the value of `declaration`, the project needs to build type declarations since it’s an intermediary package.

Maybe a top-level app could avoid emitting declarations, but this project can't.

**Comment by theAlexPatin** [comment]
Having this issue myself. Also need to emit declarations for my project.

**Comment by aemabit** [comment]
I have the same issue on my project, when add multiples validators in the same object. My top router (using TRPC) show the follow error:

`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed. (typescript)`

**Comment by Ismaele-silla** [comment]
Having the same issue and I don't have any idea on how to fix it. I used OP's temporary solution suggested in their first post, but this issue is been bugging me for months and I think it will be an even greater pain for me in the future, since I expect my schema to become bigger.

**Comment by hristod** [comment]
I am having the exact same problem. Any news on a way to go around this limitation?

**Comment by Meuko** [comment]
> I am having the exact same problem. Any news on a way to go around this limitation?

Ran into this yesterday too. Setting `declaration: false` doesn't even work, not that it should even be the real fix.. I just went ahead and marked my zod schema as type `any`, that's the only way I could temporarily get rid of this error.

**Comment by hristod** [comment]
I actually solved my problem by splitting a schema that had a pretty big union schema into parts, so it's more manageable. This is a a specific case, but maybe it would help someone in a similar situation. Here's a simplified example of what I did:

```typescript
const reallyBigUnionSchema = z.union('component', [
  schema1,
  schema2,
  schema3,
  schema4,
  schema5,
  schema6,
  schema7,
  schema8,
  schema9,
]);

// Turns into

const vol1 = z.union([
  schema1,
  schema2,
  schema3,
]);

const vol2 = z.union([
  schema4,
  schema5,
  schema6,
]);

const vol3 = z.union([
  schema7,
  schema8,
  schema9,
]);

type TSchema = z.infer<typeof vol1 | typeof vol2 | typeof vol3>;

export const combined: z.ZodType<TSchema>  = z.union([vol1, vol2, vol3]);

```

Note: In my case I actually use `discriminatedUnion` instead of a `union` everywhere except the last row, but that's because it suits my specific case.

I hope this helps someone :)
Cheers!

**Comment by Sebbones** [comment]
Here to share my latest problem:

I encountered a similar issue with one of my type libraries today. The problem stemmed from not exporting one of the types in a complex type chain. As a result, TypeScript tried to infer all the types behind that unexported type instead of using it directly because it couldn't access the type in my calling package. Once I exported the type from the library, everything worked as expected.

Here's an example to illustrate:

Library package
```ts
import { MoreComplexType } from './type' // <- also exported from lib
/*not exported*/ type SomeComplexType<X> = {
    doStuff<P extends string>(): MoreComplexType<P>
}
export function createSomething<M>(builder: () => M): SomeComplexType<M> {};
```

Application package
```ts
import {createSomething} from 'lib'

interface Model { ... }

const something = createSomething(() => model<Model>()) // <- breaks
const somethingExplicit = createSomething<Model>(() => model<Model>()) // <- breask event with an explicit annotation
```

In this case, TypeScript tried to infer `SomeComplexType` because it wasn't accessible in the app package. After exporting `SomeComplexType` from the library, it worked just fine and TypeScript used `SomeComplexType` correctly in the app package.

Maybe it help someone

**Comment by k7** [comment]
I found a post that works. [Dealing with inferred types exceeding serializable length](https://lorefnon.me/2023/11/28/fixing-inferred-types-exceeding-serializable-length/)

```ts
const Department = z.object({
    name: z.string()
})

type IDepartment = z.output<typeof Department>;
type IDepartmentIn = z.input<typeof Department>;

// Explicit type for the runtime schema of Department
export interface IDepartmentRT extends z.ZodType<IDepartment, z.ZodTypeDef, IDepartmentIn> {}

export const Company = z.object({
    name: z.string(),
    departments: (Department as IDepartmentRT).array(),
});

type ICompany = z.output<typeof Company>;
type ICompanyIn = z.input<typeof Company>;
```

**Comment by wyqydsyq** [comment]
In my case this was caused by having a huge merged enum that was exported `as const` then used to construct a few `z.nativeEnum()`s in a few places across a few schemas in a big project, removing the `as const` resolved it.

**Comment by igloo1505** [comment]
Hi guys... I just wanted to add my solution. Some people mentioned something similar, but I thought I'd specify a bit more. I had the same issue when I was using the syntax:

```ts
const someArray = [
] as const;
```

But generating an actual enum and changing the zod method from `z.enum` to `z.nativeEnum` removed the issue completely. I know it's super trivial to generate one, but I'll add my function below just to make life easy...

```ts
export class DevelopmentOutput implements DevelopmentOutputFunctionPropMap {
    constructor(public initialContent = "") {

    }

    arrayToEnum<T extends object>(props: ArrayToEnumStringProps<T>): string {
        let body = `export enum ${props.enumName} {\n`

        for (const _s of props.arr) {
            const s = typeof _s === "string" ? _s : props.getKey(_s)
            body += `    "${s}" = "${s}",\n`
        }
        body += "}"
        return body
    }
...
```

and the type:

```ts
export type ArrayToEnumStringProps<T extends object> = {
      enumName: string
} & (
{
    arr: T[],
    getKey: (val: T) => string
} | {
    arr: string[]
    getKey: never
}
)
```

**Comment by amritk** [comment]
Has this been solved in Zod 4 by any chance?

**Comment by gtflip** [comment]
> Has this been solved in Zod 4 by any chance?

I don't know if it's been solved, but it sounds like it could be:  https://zod.dev/v4#100x-reduction-in-tsc-instantiations

**Comment by evilmastermind** [comment]
> Has this been solved in Zod 4 by any chance?

it was solved in v4 for my schemas :)

**Comment by pauldraper** [comment]
https://zod.dev/v4#100x-reduction-in-tsc-instantiations is irrelevant.

And FWIW, yes it still happens. Though perhaps is better.

**Comment by sudo-vaibhav** [comment]
still seeing this issue, i wonder if there is any diagnostic method to actually find massive enums or big as const declarations in codebase.

I seriously feel we are underequipped on tooling side in terms of being able to debug these issues, currently it feels like a lot of guesswork

**Comment by gabrielbryk** [comment]
@sudo-vaibhav Feeling the same here, I have a zodv4 schema that is pretty big which works find using tsc but dosen't work with tsgo due too TS7056, seems related to  microsoft/typescript-go#2060
