### ISSUE TITLE
Access to value in `.catch` that failed to parse.

### ISSUE THREAD

**Issue by andrejpavlovic** [colinhacks/zod#1933]
I'd like to be able to access the value that failed parsing in `.catch` and do something with it. For example:

```typescript
const schema = z
  .discriminatedUnion("type", [
    z.object({ type: z.literal("type1") }),
    z.object({ type: z.literal("unknown"), value: z.unknown() })
  ])
  .catch((val: unknown) => ({ type: "unknown" as const, value: val }));

const result = schema.parse({ type: "some-other-type" });
// result would look like
// {type: "unknown", original: { type: "some-other-type" }}
```

Then in other places I can maybe log what the original value was, or try to do some more parsing in the `.catch` callback itself

**Comment by rotu** [comment]
I think this is fixed?

The above code gives me this value for `result`:
```js
{
  type: 'unknown',
  value: { error: [Getter], input: { type: 'some-other-type' } }
}
```

**Comment by andrejpavlovic** [comment]
I think since my post the first parameter in `catch` callback is the error. It still doesn't provide the actual value.

**Comment by kachkaev** [comment]
Hmmm looks like the input is passed indeed:

https://github.com/colinhacks/zod/blob/c4458caadc24f25063b6a5d0dbbbc9e1d6d60735/src/types.ts#L470-L473

`git bame` refers to https://github.com/colinhacks/zod/commit/ac0135e00df75abd57a93a4816fe0fdaa31e94e8

**Comment by andrejpavlovic** [comment]
Ah, that makes sense. Issue closed!

**Comment by andrejpavlovic** [comment]
@rotu So this should work:

```typescript
const schema = z
  .discriminatedUnion("type", [
    z.object({ type: z.literal("type1") }),
    z.object({ type: z.literal("unknown"), value: z.unknown() })
  ])
  .catch(result => ({ type: "unknown" as const, value: result.input }));
```
