### ISSUE TITLE
refine() function gets called even when parser already failed

### ISSUE THREAD

**Issue by ctollerud** [colinhacks/zod#2113]
Using version 3.20.6

In certain scenarios, refine gets called even when the parser has already failed.   It seems like including a z.custom() can trigger this.

What's worse is that the type flowing into the refine's function (x) is different than what typescript thinks it is

Here's a minimal example:
```Typescript
const example1 = z
	.custom<number>(x => typeof x === 'number')
	.transform(x => String(x))
	.refine(x => {
		console.log(typeof x); // prints 'Object'
		console.log("I get called even though I shouldn't!!!");
		return true;
	})
	.safeParse({}); //will fail because it is not a number

console.log(example1.success); // false (like it should be)
```
And here's a more complex example with the same issue
```Typescript
const example2 = z
	.union([z.number(), z.string(), z.custom<number>(x => typeof x === 'number')])
	.refine(() => true)
	.pipe(z.any())
	.or(z.date())
	.pipe(z.any())
	.refine(x => {
		console.log("I get called even though I shouldn't!!!!!!!!!");
		return true;
	})
	.safeParse(true); // will fail immediately because it's a bool
```

As a work-around, using `.transform(x,ctx)=>...) ` approach to validate seems to work.

**Comment by JacobWeisenburger** [comment]
I have confirmed that this works as stated by @ctollerud

**Comment by ctollerud** [comment]
In case it helps, here's a more general repeatable pattern:
It looks any failure that's caused by refine will not prevent any future refines from being called.
```Typescript
const result = z
	.unknown() //let everything through
	.refine(() => false) // force failure for everything here
	.refine(x => {
		console.log('I should not get called');
		return x;
	})
	.refine(x => {
		console.log('I should also not get called');
		return x;
	})
	.safeParse('asdf');
console.log(result.success); // fails (correctly)
```
It also looks like failure inside of `z.string().regex(...)` can trigger this behavior:
https://stackoverflow.com/questions/74806649/zod-refine-arguments-provide-the-unvalidated-raw-data

Here's a minimal repro of that as well:
```Typescript
const result2 = z
	.string()
	.regex(/123/)
	.refine(x => {
		console.log('I should not be called');
		return x;
	})
	.safeParse('234');

console.log(result2.success); // fails (correctly)
```

**Comment by colinhacks** [comment]
This is fixed in Zod 3.21

**Comment by JacobWeisenburger** [comment]
> This is fixed in Zod 3.21

Confirmed

**Comment by Darkhogg** [comment]
I am still seeing this problem after a `.transform`, which is especially problematic since the transform is not applied and the code might crash.  This a (very stupid) example that uses a transform to change the type:

```
import z from 'zod'

const schema = z.string()
  .refine((str) => str.match(/^[0-9]+$/))
  .transform((str) => parseInt(str))
  .refine((num) => num.toExponential())

console.log(schema.parse('123'))
console.log(schema.parse('1234'))
console.log(schema.parse('1234a'))
```

First to lines print a number. Third line crashes because the last `.refine` gets executed with a `string` instead of a `number`, and the code does not expect that.

**Comment by JacobWeisenburger** [comment]
This is not working correctly again.

```ts
const result = z
    .unknown() //let everything through
    .refine( () => false ) // force failure for everything here
    .refine( x => {
        console.log( 'I should not get called' )
        return x
    } )
    .refine( x => {
        console.log( 'I should also not get called' )
        return x
    } )
    .safeParse( 'asdf' )
console.log( result.success ) // fails (correctly)

const result2 = z
    .string()
    .regex( /123/ )
    .refine( x => {
        console.log( 'I should not be called' )
        return x
    } )
    .safeParse( '234' )

console.log( result2.success ) // fails (correctly)
```

**Comment by Darkhogg** [comment]
Are this and #2192 the same issue? they seem to be...

**Comment by JacobWeisenburger** [comment]
they are very similar

**Comment by akomm** [comment]
Can the stale bot not be configured to not mark issues that are `bug-confirmed`?

I think the idea behind built-in refinements like .min to not be fatal at this point we already know something is for example of type number and so its safe to pass it to refine that depends on this. But this assumption is wrong. You might have refinements based on assumption about the previously validated data. For example that something is not zero, or that something is a sortable non-empty string, example:

```ts
const dateIsoRegex = /^\d{4}-\d{2}-\d{2}$/
const dateIso = z
    .string()
    .refine(s => s.match(dateIsoRegex) && !Number.isNaN(Date.parse(s)), "Invalid Date")
    .brand("DateIso")

const dateIsoRange = z
    .object({from: dateIso, thru: dateIso})
    .refine(({from, thru}) => from < thru, "from > thru")
    .brand("DateIsoRange")
```

Besides producing "Invalid Date" error, this one will randomly, depending on the input, also tell that from is greater than thru.

Current workaround:
```ts
const dateIso = z
  .string()
  .superRefine((v, ctx) => {
    if (!v.match(dateIsoRegex) || Number.isNaN(Date.parse(v))) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        fatal: true,
        message: "Invalid Date",
      })
    }
  })
```
