### ISSUE TITLE
Zod 2 - parseAsync breaks unions of objects

### ISSUE THREAD

**Issue by mpartel** [colinhacks/zod#230]
```typescript
import * as z from 'zod';

const Schema = z.union([
    z.object({
        ty: z.literal('A'),
    }),
    z.object({
        ty: z.literal('B'),
    }),
]);

(async () => {
  const obj = { ty: 'A' };
  console.log(Schema.parse(obj));  // Works
  console.log(await Schema.parseAsync(obj));  // Works with 1.11.10, breaks with 2.0.0-beta.21
})();
```

With Zod 2.0.0-beta.21, the `parseAsync` call fails with

```json
{
  "code": "invalid_literal_value",
  "expected": "B",
  "path": [
    "ty"
  ],
  "message": "Input must be \"B\""
}
```

The objects wrapping the literals are important. A schema of `z.union([z.literal('A'), z.literal('B')])` worked fine.

**Comment by colinhacks** [comment]
Very weird, I'll look into this when I have time. Also a PR is welcome.

**Comment by colinhacks** [comment]
Finally cracked this one. There were some errors that weren't being properly caught when the input to `.parse` is missing keys that the schema expects. Fixed in beta 23. Thanks for pointing this out! 

CC @jrwm @mpartel

**Comment by mpartel** [comment]
Thanks for the fix and for zod in general!

**Comment by pepakriz** [comment]
@colinhacks Hi, when I try to run the snippet from the top, I still get an error with `parseAsync`. Tested with beta.23 and beta.24. The same result.
@mpartel Can you confirm that I'm right? Or am I doing something wrong?

Thank you

**Comment by mpartel** [comment]
Can confirm with beta.23 and beta.24.

**Comment by colinhacks** [comment]
Looks like there were multiple bugs in play here. I fixed one problem with how objects get parsed but there was another issue with unions. I can confirm the original snippet now runs correctly with beta 25 (and it's been added to the test suite!).

**Comment by pepakriz** [comment]
@colinhacks Thank you, the original snippet works correctly. But I have another one:

```
import * as z from 'zod';

const Schema = z.union([
	z.object({
		statusCode: z.literal(200),
		body: z.object({
			id: z.string(),
		}),
	}),
	z.object({
		statusCode: z.literal(403),
		body: z.object({
			message: z.string(),
			reason: z.string().nullable(),
		}),
	}),
]);

(async () => {
	const obj = { statusCode: 200, body: { id: "f8a2ebc9-72ba-4f45-ad4d-16f956259ed3" } };
	console.log(Schema.parse(obj)); // Works
	console.log(await Schema.parseAsync(obj)); // Error
})();
```

**Comment by pepakriz** [comment]
@colinhacks Hi. I've tested the snippet from my previous post again and it still failing with v2. But it works on v3. It works also with v3-alpha.1 so the fix must be somewhere in https://github.com/colinhacks/zod/commit/278a4f56afc0311c9044a3dbfb46eeffc16cfad7

So my question is what is your plan for v2? Do you want to release it or you'll skip it? I'd like to start to use some v2 features that'll improve my code type safety. V2 seems pretty stable except this issue and v3 is in alpha.

**Comment by colinhacks** [comment]
This is working for me on v2 beta 29. Are you sure you're using the latest beta?

To answer your other question, I'm planning to skip v2 and release v3 into beta shortly. There are very few changes from v2 to v3, basically just the internal implementation of transformers. v3 will be in beta for a short time before a general release, as long as no other major issues arise.

**Comment by shakerii** [comment]
I'm having the same issue, I'm using version 3.22.4
