### ISSUE TITLE
z.default in doc but only z._default available in @zod/mini

### ISSUE THREAD

**Issue by channyeintun** [colinhacks/zod#4136]
In documentation, 
```
const defaultTuna = z.default(z.string(), "tuna");
 
defaultTuna.parse(undefined); // => "tuna"
```

But actually, only `z._default` is available.

**Comment by colinhacks** [comment]
Fixed, thanks!

**Comment by leo91000** [comment]
@colinhacks I still have the issue in zod v4.0.5 when importing from zod/mini : 

<img width="2057" height="136" alt="Image" src="https://github.com/user-attachments/assets/239cdc4a-d455-4225-8796-e5c3ed4ddfe3" />

EDIT : According to the doc, `_default` might be expected name, maybe it's because default is reserved keyword when treeshaking is available

**Comment by a-eid** [comment]
@colinhacks there is no z.default
