### ISSUE TITLE
v4: z.int().nonnegative is not a function

### ISSUE THREAD

**Issue by RobinTail** [colinhacks/zod#4162]
While `z.number().int()` is deprecated in favor of `z.int()`, I'm experiencing this issue:

```ts
import { z } from "zod";

const a = z.int().nonnegative();
```

TypeError: z.int(...).nonnegative is not a function

`¯\_(ツ)_/¯ `

```
zod@4.0.0-beta.20250414T061543
@zod/core@0.5.0
```

**Comment by spaceemotion** [comment]
Just wanted to add that the same is happening for `z.int().positive()`. Just got the same error now.

**Comment by robsimmons** [comment]
`.gte(n)` as well, presumably also the other comparison functions

**Comment by RobinTail** [comment]
`z.email().max(32)` too

So, basically, every shorthand-schema lacks the ability to add more checks/refinements to it.

**Comment by colinhacks** [comment]
Fixed in `@zod/core@0.7.0` and latest betas

**Comment by RobinTail** [comment]
Not fixed, @colinhacks 

```ts
z.int().max()
```

```
z.int(...).max is not a function
```

core 0.7.1

**Comment by robsimmons** [comment]
I'm getting the same result as @RobinTail for `gte` in `4.0.0-beta.20250418T073619`, still getting `TypeError: z.int(...).gte is not a function` (cc @colinhacks)

**Comment by bobhigs** [comment]
It looks like it's just a matter of changing:
https://github.com/colinhacks/zod/blob/5a01d8df5b3717223e9a6102e13d591a23c49986/packages/zod/src/schemas.ts#L736

to `ZodNumber.init(inst, def);`

I'll make a PR with this change and a bunch of tests in the next day or so.

**Comment by RobinTail** [comment]
Please tag the following issue if you make such PR, @bobhigs : 
https://github.com/colinhacks/zod/issues/4228
