### ISSUE TITLE
v4: Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Edge Runtime

### ISSUE THREAD

**Issue by samnang** [colinhacks/zod#4273]
I encountered a warning while upgrading to version 4 in my Next.js project:

```
 ⚠ DynamicCodeEvaluationWarning: Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Edge Runtime
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation
    at eval (webpack-internal:///(middleware)/./node_modules/@zod/core/dist/esm/util.js:175:9)

```

It appears that the complaint originates from:

https://github.com/colinhacks/zod/blob/46e96c77af3a72fc4b76558654fcd3f3f8c52b8e/packages/core/src/util.ts#L308-L314 

Could someone clarify the purpose of this function and its necessity?

**Comment by jeremyjacob** [comment]
It's likely to check if code-gen optimizations can be preformed for schema parsing. Edge runtimes like Vercel's or Cloudflare's don't allow `eval()` or `new Function()`, precluding these kinds of optimizations. This check raises a warning on Vercel because it uses `new Function()` in a try/catch to test if this behavior is allowed in the current execution environment.

**Comment by alexanderniebuhr** [comment]
Did anyone got it working inside Cloudflare Workers?

**Comment by tobytheghost** [comment]
We've also seen this get flagged up in our CSP strict environments

**Comment by ChillyBots** [comment]
+1 - this will be a blocker for anything with strict CSP and is wonderfully ironic
By testing to see if the environment allows eval/ new Func, you're calling new Func - which will throw errors / be disallowed. To be clear, this will crash if run in a strict CSP env

I think the best way you can handle this gracefully is via a flag/argument/env var when running Zod so it can be set on the server level, with the default being `evalSupport: false` for security's sake. It can then be opted in for bare-metal speed freaks who throw caution to the wind. 

...or potentially as a separate module which can be opted into, so the danger code is never even built.

**Comment by colinhacks** [comment]
I'll look into a `z.config({ noEval: true })` configuration setting to alleviate this.

**Comment by tobimori** [comment]
Cloudflare Workers will support new Function/eval starting June 1st.

**Comment by colinhacks** [comment]
This is now fixed on Next.js Edge Runtime. I haven't tested Cloudflare Workers, but if others experience issues there please open a new issue.

**Comment by ChillyBots** [comment]
@colinhacks I've just tried rolling the production version out again, and unfortunately the issue persists

`zod:  3.25.20`

`script-src: 'eval' blocked by 'script-src' directive of the policy`

**Comment by jafri** [comment]
@colinhacks still not working with "Code generation from strings disallowed for this context" in Cloudflare Workers

**Comment by richard-viney** [comment]
I'm getting exceptions reported from inside `allowsEval` when using Zod on a frontend with strict CSP rules: `csp_violation: 'eval' blocked by 'script-src' directive`.

We can ignore these reports, but a `noEval` configuration option would be great.

**Comment by andrew0li** [comment]
Any updates here? We're still needing to set `jitless` in the zod config. a `noEval` option would be awesome
