### ISSUE TITLE
v4 classic: ZodEnum type has a type error

### ISSUE THREAD

**Issue by rktyt** [colinhacks/zod#4624]
zod@3.25.51

When `"skipLibCheck": false` is specified in `tsconfig.json`, the following error occurs.
![Image](https://github.com/user-attachments/assets/caa4bf51-39d8-42c0-8c48-e22902da8936)

In the original source, `@ts-ignore` is present, but it is removed in the bundled output.
https://github.com/colinhacks/zod/blob/c58bd9b0125881caee03a408eae88ec1dc5eb18b/packages/zod/src/v4/classic/schemas.ts#L1402-L1405

**Comment by bienjamon** [comment]
For now, I rolled back to @3.25.40, and my build is working again

**Comment by lesomnus** [comment]
Seems that `zod@3.25.40` have an issue with TS2846:
```
node_modules/zod/v4/index.d.ts:1:15 - error TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file '../dist/types/v4/index' instead?

1 export * from "../dist/types/v4/index.d.ts";
```

In my case, `zod@3.25.43` works fine.
Note that im using `typescript@5.8.3`.

**Comment by colinhacks** [comment]
Thanks, fixed in 3.25.55. Working on better tests for this as well.

**Comment by rktyt** [comment]
@colinhacks 
The type error still occurs in version 3.25.55.

https://github.com/colinhacks/zod/commit/44141ea1dbd48403f14704386119884aeda5cb27#diff-db42621d1d6e085777e8710328893bbd1ca6a1f3b12709de27f69a37d3d94cf9

Since the `/** @ts-ignore ... */` comments remain in the `dist` output, shouldn't it be `/** @ts-ignore Cast variance */` instead of `/* @ts-ignore Cast variance */`?

**Comment by bwateratmsft** [comment]
I'm experiencing this as well with 3.25.55.

**Comment by colinhacks** [comment]
Fixed in 3.25.56 (for real this time) 😅
