### ISSUE TITLE
Incorrect type of def in discriminatedUnion in v4

### ISSUE THREAD

**Issue by brabeji** [colinhacks/zod#4873]
Hello! I need to use the discriminator key in my library but it's presumably incorrectly typed as `$ZodUnionDef` instead of `$ZodDiscriminatedUnionDef` (excuse the screenshot):

<img width="745" height="330" alt="Image" src="https://github.com/user-attachments/assets/d2914f0e-ec8d-46bc-ae84-d4cb6b138848" />

I would like to be sure that this is unintentional and that the discriminator property won't disappear in future versions.

**Comment by brabeji** [comment]
I'm accessing the `def` property through the most specific type possible (type of literal zod schema, as opposed to generic/broad type). This should work out of the box imo.

**Comment by Zegnat** [comment]
I bumped into this today too.

It looks like there is a difference between `du.def` and `du._zod.def`, where the first exposes the `$ZodUnionDef` and the latter the `$ZodDiscriminatedUnionDef`. This looks like a bug to me.

I will be using `du._zod.def.discriminator` for typed access now. But it feels a little icky to be using the internal accessor for this, especially because the disciminator has been copied to def. This is just a type error somewhere.

**Comment by colinhacks** [comment]
Fixed in 4.0.5.

**Comment by brabeji** [comment]
@colinhacks Seems still broken in 4.0.5 https://codesandbox.io/p/sandbox/vkmmxk

**Comment by Zegnat** [comment]
It looks like [the 4.0.5 release](https://github.com/colinhacks/zod/releases/tag/v4.0.5) was made from commit https://github.com/colinhacks/zod/commit/45afab0f846dffd591362b6f770017507eb185b5, almost ~21 hours before the commit that fixed this issue https://github.com/colinhacks/zod/commit/a9c120e0d6abf82aefd342aac9668cbf8ca28786. When I check out the latest development version straight from GitHub this issue does seem to be fixed.

We›ll just have to wait for a 4.0.6 release.

**Comment by brabeji** [comment]
@Zegnat thanks for checking!
