### ISSUE TITLE
Tuples in unions does not get validated since v3.9.1

### ISSUE THREAD

**Issue by screendriver** [colinhacks/zod#668]
Following schema

```ts
const eventsSchema = z.union([
    z.object({
      eventName: z.literal('foo'),
      eventPayload: z.tuple([z.number().nonnegative(), z.number().nonnegative()])
    }).strict(),
    z.object({
      eventName: z.literal('bar'),
      eventPayload: z.string().email()
    }).strict()
]);
```

failed before `v3.9.1` with following data

```ts
const data = {
  "eventName": "foo",
  "eventPayload": [0, -60]
};
const parseResult = eventsSchema.safeParse(data);
// parseResult.success === true
```

but since `v3.9.1` `zod` does not validate the `-60` value anymore as `.nonnegative()`. Parsing is always successful whereas before `v3.9.1` it failed (which is the expected behaviour)

**Comment by anguskeatinge** [comment]
I have a similar issue, the `email` part of the validation is broken for both `union` and `or`

I only just moved from `v3.4.1` to `v3.9.1` so the regression was introduced somewhere in there.

Here are some examples:
```jsx
const BrokenSchema = z.union([
    z.object({
        email: z.string().email(),
    }),
    z.object({
        email: z.literal(null),
    }),
]);
// same as above
const BrokenSchema2 = z
    .object({
        email: z.string().email(),
    })
    .or(
        z.object({
            email: z.literal(null),
        }),
    );

const res1 = BrokenSchema.safeParse({ email: 'asdf' });
expect(res1.success).toBe(false); // this test DOES NOT pass

const res2 = BrokenSchema.safeParse({ email: 9 });
expect(res2.success).toBe(false); // this test DOES pass
```

I'm a little bit taken aback that this didn't come up in zod's unit tests.

**Comment by colinhacks** [comment]
I'll look into this today.

**Comment by colinhacks** [comment]
Should be fixed in 3.9.2+

**Comment by ohana54** [comment]
Thanks @colinhacks, for us the case that @oleg-codaio presented still doesn't work (in 3.9.4).
Simplified example: https://codesandbox.io/s/eager-yonath-fb3mq

```
z.union([z.number(), z.string().refine(() => false)]).parse("a");
```

**Comment by alax** [comment]
Yes, running v3.9.5, this is an issue for us at Deletype as well.

It seems any union that includes a string with a refiner attached (like ohana54's example) just doesn't work. Here is what is failing for us:

```typescript
z.union([
    z.number(),
    z.string().refine(val => !isNaN(Number(val)))
])
```

**Comment by colinhacks** [comment]
Oops looks like I failed to fully roll back the changes that caused this error. I've confirmed that all the above cases are working in Zod v3.9.8+.

**Comment by oleg-codaio** [comment]
Thanks! Hopefully we have unit tests too to help catch any future regressions.
